version: '3'

services:
  testapi:
    image: testapi
    build:
      context: .
      dockerfile: TestAPI/Dockerfile
      args:
        - http_proxy=http://proxy:8080
        - https_proxy=http://proxy:8080
        - no_proxy=localhost
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - http_proxy=http://proxy:8080
      - https_proxy=http://proxy:8080
      - no_proxy=localhost
  testclient:
    image: testclient
    build:
      context: .
      dockerfile: TestClient/Dockerfile
      args:
        - http_proxy=http://proxy:8080
        - https_proxy=http://proxy:8080
        - no_proxy=localhost,testapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - http_proxy=http://proxy:8080
      - https_proxy=http://proxy:8080
      - no_proxy=localhost,testapi
