version: '3'

services:
  testapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  testclient:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

